version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "empresa"
    ports:
      - "3350:3306"
    volumes:
      - ./empresa.sql:/docker-entrypoint-initdb.d/init.sql
    # 👇 ESTO LE ENSEÑA A DOCKER CÓMO SABER SI MYSQL YA TERMINÓ
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 10s
      retries: 10
      interval: 5s

  app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8081:5000"
    # 👇 MODIFICADO: Ahora espera a que el healthcheck de arriba sea "healthy"
    depends_on:
      db:
        condition: service_healthy